{{- if .Values.control.aws.accessKeyId -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgdog-control.control.fullname" . }}-aws-creds
  labels:
    {{- include "pgdog-control.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.control.aws.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ required "control.aws.secretAccessKey is required when accessKeyId is set" .Values.control.aws.secretAccessKey | quote }}
  {{- with .Values.control.aws.sessionToken }}
  AWS_SESSION_TOKEN: {{ . | quote }}
  {{- end }}
{{- end -}}
