{{- if and .Values.raft.enabled (not ((.Values.raft.secret | default dict).tokenKey)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgdog-control.raft.fullname" . }}
  labels:
    {{- include "pgdog-control.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ include "pgdog-control.raft.token" . | b64enc | quote }}
{{- end }}
