{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-secrets" .Release.Name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}-control
type: Opaque
data:
  {{- if $existingSecret }}
  SESSION_KEY: {{ index $existingSecret.data "SESSION_KEY" }}
  {{- else }}
  SESSION_KEY: {{ randAlphaNum 64 | b64enc }}
  {{- end }}
