{{- if not (.Values.control.config.auth | default dict).cookie_secret -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace (printf "%s-secrets" .Release.Name) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "pgdog-control.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and $existing (index $existing.data "cookie_secret") }}
  cookie_secret: {{ index $existing.data "cookie_secret" }}
  {{- else }}
  cookie_secret: {{ randAlphaNum 64 | b64enc }}
  {{- end }}
{{- end -}}
